type Region = 'NTSC' | 'PAL'

type NesGameEntry = {
  title: string
  region: Region[]
}

export const games: NesGameEntry[] = [
  { title: 'The 3-D Battles of WorldRunner', region: ['NTSC'] },
  { title: '8 Eyes', region: ['NTSC'] },
  { title: '10-Yard Fight', region: ['NTSC', 'PAL'] },
  { title: '720°', region: ['NTSC'] },
  { title: '1942', region: ['NTSC'] },
  { title: '1943: The Battle of Midway', region: ['NTSC'] },
  { title: 'Abadox: The Deadly Inner War', region: ['NTSC'] },
  { title: 'The Addams Family', region: ['NTSC', 'PAL'] },
  { title: "The Addams Family: Pugsley's Scavenger Hunt", region: ['NTSC', 'PAL'] },
  { title: 'Advanced Dungeons & Dragons: DragonStrike', region: ['NTSC'] },
  { title: 'Advanced Dungeons & Dragons: Heroes of the Lance', region: ['NTSC'] },
  { title: 'Advanced Dungeons & Dragons: Hillsfar', region: ['NTSC'] },
  { title: 'Advanced Dungeons & Dragons: Pool of Radiance', region: ['NTSC'] },
  { title: 'Adventure Island', region: ['NTSC'] },
  { title: 'Adventure Island Classic', region: ['PAL'] },
  { title: 'Adventure Island Classic in the Pacific', region: ['PAL'] },
  { title: 'Adventure Island II', region: ['NTSC'] },
  { title: 'The Adventure Island Part II', region: ['PAL'] },
  { title: 'Adventure Island 3', region: ['NTSC'] },
  { title: 'Adventures in the Magic Kingdom', region: ['NTSC', 'PAL'] },
  { title: 'The Adventures of Bayou Billy', region: ['NTSC', 'PAL'] },
  { title: 'Adventures of Dino Riki', region: ['NTSC'] },
  { title: "The Adventures of Gilligan's Island", region: ['NTSC'] },
  { title: 'Adventures of Lolo', region: ['NTSC', 'PAL'] },
  { title: 'Adventures of Lolo 2', region: ['NTSC', 'PAL'] },
  { title: 'Adventures of Lolo 3', region: ['NTSC', 'PAL'] },
  { title: 'The Adventures of Rad Gravity', region: ['NTSC', 'PAL'] },
  { title: 'The Adventures of Rocky and Bullwinkle and Friends', region: ['NTSC'] },
  { title: 'Adventures of Tom Sawyer', region: ['NTSC'] },
  { title: 'Air Fortress', region: ['NTSC', 'PAL'] },
  { title: 'Airwolf', region: ['NTSC', 'PAL'] },
  { title: "Al Unser Jr.'s Turbo Racing", region: ['NTSC'] },
  { title: 'Turbo Racing', region: ['PAL'] },
  { title: "Alex Demeo's Race America", region: ['NTSC'] },
  { title: 'Corvette ZR-1 Challenge', region: ['PAL'] },
  { title: 'Alfred Chicken', region: ['NTSC', 'PAL'] },
  { title: 'Alien 3', region: ['NTSC', 'PAL'] },
  { title: 'All-Pro Basketball', region: ['NTSC'] },
  { title: 'Alpha Mission', region: ['NTSC', 'PAL'] },
  { title: 'Amagon', region: ['NTSC'] },
  { title: 'American Gladiators', region: ['NTSC'] },
  { title: 'Anticipation', region: ['NTSC', 'PAL'] },
  { title: 'Arch Rivals', region: ['NTSC', 'PAL'] },
  { title: 'Archon', region: ['NTSC'] },
  { title: 'Arkanoid', region: ['NTSC'] },
  { title: "Arkista's Ring", region: ['NTSC'] },
  { title: 'Asterix', region: ['PAL'] },
  { title: 'Astyanax', region: ['NTSC', 'PAL'] },
  { title: 'Athena', region: ['NTSC'] },
  { title: 'Athletic World', region: ['NTSC', 'PAL'] },
  { title: 'Attack of the Killer Tomatoes', region: ['NTSC', 'PAL'] },
  { title: 'Aussie Rules Footy', region: ['PAL'] },
  { title: 'Back to the Future', region: ['NTSC'] },
  { title: 'Back to the Future Part II & III', region: ['NTSC'] },
  { title: 'Bad Dudes', region: ['NTSC'] },
  { title: 'Bad Dudes vs. DragonNinja', region: ['PAL'] },
  { title: 'Bad News Baseball', region: ['NTSC'] },
  { title: 'Bad Street Brawler', region: ['NTSC'] },
  { title: 'Balloon Fight', region: ['NTSC', 'PAL'] },
  { title: 'Banana Prince', region: ['PAL'] },
  { title: 'Bandai Golf: Challenge Pebble Beach', region: ['NTSC'] },
  { title: 'Bandit Kings of Ancient China', region: ['NTSC'] },
  { title: 'Barbie', region: ['NTSC', 'PAL'] },
  { title: "The Bard's Tale", region: ['NTSC'] },
  { title: "Barker Bill's Trick Shooting", region: ['NTSC', 'PAL'] },
  { title: 'Base Wars', region: ['NTSC'] },
  { title: 'Baseball', region: ['NTSC', 'PAL'] },
  { title: 'Baseball Simulator 1.000', region: ['NTSC'] },
  { title: 'Baseball Stars', region: ['NTSC'] },
  { title: 'Baseball Stars 2', region: ['NTSC'] },
  { title: 'Bases Loaded', region: ['NTSC'] },
  { title: 'Bases Loaded II: Second Season', region: ['NTSC'] },
  { title: 'Bases Loaded 3', region: ['NTSC'] },
  { title: 'Bases Loaded 4', region: ['NTSC'] },
  { title: 'Batman: The Video Game', region: ['NTSC', 'PAL'] },
  { title: 'Batman: Return of the Joker', region: ['NTSC', 'PAL'] },
  { title: 'Batman Returns', region: ['NTSC', 'PAL'] },
  { title: 'Battle Chess', region: ['NTSC'] },
  { title: 'The Battle of Olympus', region: ['NTSC', 'PAL'] },
  { title: 'Battle Tank', region: ['NTSC'] },
  { title: 'Battleship', region: ['NTSC', 'PAL'] },
  { title: 'Battletoads', region: ['NTSC', 'PAL'] },
  { title: 'Battletoads & Double Dragon', region: ['NTSC', 'PAL'] },
  { title: 'Beetlejuice', region: ['NTSC'] },
  { title: 'Best of the Best: Championship Karate', region: ['NTSC', 'PAL'] },
  { title: 'Bigfoot', region: ['NTSC', 'PAL'] },
  { title: "Bill & Ted's Excellent Video Game Adventure", region: ['NTSC'] },
  { title: "Bill Elliott's NASCAR Challenge", region: ['NTSC'] },
  { title: 'Bionic Commando', region: ['NTSC', 'PAL'] },
  { title: 'The Black Bass', region: ['NTSC'] },
  { title: 'Blades of Steel', region: ['NTSC', 'PAL'] },
  { title: 'Blaster Master', region: ['NTSC', 'PAL'] },
  { title: 'The Blue Marlin', region: ['NTSC'] },
  { title: 'The Blues Brothers', region: ['NTSC', 'PAL'] },
  { title: 'Bo Jackson Baseball', region: ['NTSC'] },
  { title: 'Bomberman', region: ['NTSC'] },
  { title: 'Bomberman II', region: ['NTSC'] },
  { title: 'Dynablaster', region: ['PAL'] },
  { title: "Bonk's Adventure", region: ['NTSC'] },
  { title: 'Boulder Dash', region: ['NTSC', 'PAL'] },
  { title: 'A Boy and His Blob: Trouble on Blobolonia', region: ['NTSC', 'PAL'] },
  { title: "Bram Stoker's Dracula", region: ['NTSC', 'PAL'] },
  { title: 'Break Time: The National Pool Tour', region: ['NTSC'] },
  { title: 'BreakThru', region: ['NTSC'] },
  { title: 'Bubble Bobble', region: ['NTSC', 'PAL'] },
  { title: 'Bubble Bobble Part 2', region: ['NTSC'] },
  { title: "Bucky O'Hare", region: ['NTSC', 'PAL'] },
  { title: 'The Bugs Bunny Birthday Blowout', region: ['NTSC'] },
  { title: 'The Bugs Bunny Blowout', region: ['PAL'] },
  { title: 'The Bugs Bunny Crazy Castle', region: ['NTSC'] },
  { title: "Bump 'n' Jump", region: ['NTSC'] },
  { title: 'Burai Fighter', region: ['NTSC', 'PAL'] },
  { title: 'BurgerTime', region: ['NTSC'] },
  { title: 'Cabal', region: ['NTSC'] },
  { title: 'Caesars Palace', region: ['NTSC'] },
  { title: 'California Games', region: ['NTSC', 'PAL'] },
  { title: "Capcom's Gold Medal Challenge '92", region: ['NTSC', 'PAL'] },
  { title: 'Captain America and The Avengers', region: ['NTSC', 'PAL'] },
  { title: 'Captain Planet and the Planeteers', region: ['NTSC', 'PAL'] },
  { title: 'Captain Skyhawk', region: ['NTSC', 'PAL'] },
  { title: 'Casino Kid', region: ['NTSC'] },
  { title: 'Casino Kid 2', region: ['NTSC'] },
  { title: 'Castelian', region: ['NTSC', 'PAL'] },
  { title: 'Castle of Dragon', region: ['NTSC'] },
  { title: 'Castlequest', region: ['NTSC'] },
  { title: 'Castlevania', region: ['NTSC', 'PAL'] },
  { title: "Castlevania II: Simon's Quest", region: ['NTSC', 'PAL'] },
  { title: "Castlevania III: Dracula's Curse", region: ['NTSC', 'PAL'] },
  { title: 'Caveman Games', region: ['NTSC'] },
  { title: 'Championship Bowling', region: ['NTSC'] },
  { title: 'Championship Pool', region: ['NTSC'] },
  { title: 'Championship Rally', region: ['PAL'] },
  { title: 'Chessmaster', region: ['NTSC', 'PAL'] },
  { title: "Chip 'n Dale: Rescue Rangers", region: ['NTSC', 'PAL'] },
  { title: "Chip 'n Dale: Rescue Rangers 2", region: ['NTSC', 'PAL'] },
  { title: 'Chubby Cherub', region: ['NTSC'] },
  { title: 'Circus Caper', region: ['NTSC'] },
  { title: 'City Connection', region: ['NTSC', 'PAL'] },
  { title: 'Clash at Demonhead', region: ['NTSC'] },
  { title: 'Classic Concentration', region: ['NTSC'] },
  { title: 'Cliffhanger', region: ['NTSC'] },
  { title: 'Clu Clu Land', region: ['NTSC', 'PAL'] },
  { title: 'Cobra Command', region: ['NTSC'] },
  { title: 'Cobra Triangle', region: ['NTSC', 'PAL'] },
  { title: 'Code Name: Viper', region: ['NTSC'] },
  { title: 'Color a Dinosaur', region: ['NTSC'] },
  { title: 'Commando', region: ['NTSC'] },
  { title: 'Conan: The Mysteries of Time', region: ['NTSC'] },
  { title: 'Conflict', region: ['NTSC'] },
  { title: 'Conquest of the Crystal Palace', region: ['NTSC'] },
  { title: 'Contra', region: ['NTSC'] },
  { title: 'Probotector', region: ['PAL'] },
  { title: 'Contra Force', region: ['NTSC'] },
  { title: 'Cool World', region: ['NTSC'] },
  { title: 'Cowboy Kid', region: ['NTSC'] },
  { title: 'Crackout', region: ['PAL'] },
  { title: "Crash 'n the Boys: Street Challenge", region: ['NTSC'] },
  { title: 'Crystalis', region: ['NTSC'] },
  { title: 'Cyberball', region: ['NTSC'] },
  { title: 'Cybernoid: The Fighting Machine', region: ['NTSC'] },
  { title: 'Dance Aerobics', region: ['NTSC'] },
  { title: "Danny Sullivan's Indy Heat", region: ['NTSC', 'PAL'] },
  { title: 'Darkman', region: ['NTSC', 'PAL'] },
  { title: 'Dash Galaxy in the Alien Asylum', region: ['NTSC'] },
  { title: "Day Dreamin' Davey", region: ['NTSC'] },
  { title: 'Days of Thunder', region: ['NTSC', 'PAL'] },
  { title: 'Deadly Towers', region: ['NTSC'] },
  { title: 'Defender II', region: ['NTSC'] },
  { title: 'Defender of the Crown', region: ['NTSC', 'PAL'] },
  { title: 'Defenders of Dynatron City', region: ['NTSC'] },
  { title: 'Déjà Vu', region: ['NTSC', 'PAL'] },
  { title: 'Demon Sword', region: ['NTSC'] },
  { title: 'Desert Commander', region: ['NTSC'] },
  { title: 'Destination Earthstar', region: ['NTSC'] },
  { title: 'Destiny of an Emperor', region: ['NTSC'] },
  { title: 'Devil World', region: ['PAL'] },
  { title: 'Dick Tracy', region: ['NTSC'] },
  { title: 'Die Hard', region: ['NTSC', 'PAL'] },
  { title: 'Dig Dug II', region: ['NTSC'] },
  { title: 'Digger T. Rock: Legend of the Lost City', region: ['NTSC', 'PAL'] },
  { title: 'Dirty Harry', region: ['NTSC'] },
  { title: "Disney's Aladdin", region: ['PAL'] },
  { title: "Disney's Beauty and the Beast", region: ['PAL'] },
  { title: "Disney's Darkwing Duck", region: ['NTSC', 'PAL'] },
  { title: "Disney's The Jungle Book", region: ['NTSC', 'PAL'] },
  { title: "Disney's The Lion King", region: ['PAL'] },
  { title: "Disney's The Little Mermaid", region: ['NTSC'] },
  { title: 'Donkey Kong', region: ['NTSC', 'PAL'] },
  { title: 'Donkey Kong 3', region: ['NTSC', 'PAL'] },
  { title: 'Donkey Kong Classics', region: ['NTSC', 'PAL'] },
  { title: 'Donkey Kong Jr.', region: ['NTSC', 'PAL'] },
  { title: 'Donkey Kong Jr. Math', region: ['NTSC', 'PAL'] },
  { title: 'Double Dare', region: ['NTSC'] },
  { title: 'Double Dragon', region: ['NTSC', 'PAL'] },
  { title: 'Double Dragon II: The Revenge', region: ['NTSC', 'PAL'] },
  { title: 'Double Dragon III: The Sacred Stones', region: ['NTSC', 'PAL'] },
  { title: 'Double Dribble', region: ['NTSC', 'PAL'] },
  { title: 'Dr. Chaos', region: ['NTSC'] },
  { title: 'Dr. Jekyll and Mr. Hyde', region: ['NTSC'] },
  { title: 'Dr. Mario', region: ['NTSC', 'PAL'] },
  { title: 'Dragon Fighter', region: ['NTSC'] },
  { title: 'Dragon Power', region: ['NTSC'] },
  { title: 'Dragon Ball', region: ['PAL'] },
  { title: 'Dragon Spirit: The New Legend', region: ['NTSC'] },
  { title: 'Dragon Warrior', region: ['NTSC'] },
  { title: 'Dragon Warrior II', region: ['NTSC'] },
  { title: 'Dragon Warrior III', region: ['NTSC'] },
  { title: 'Dragon Warrior IV', region: ['NTSC'] },
  { title: "Dragon's Lair", region: ['NTSC', 'PAL'] },
  { title: 'Dropzone', region: ['PAL'] },
  { title: 'Duck Hunt', region: ['NTSC', 'PAL'] },
  { title: 'DuckTales', region: ['NTSC', 'PAL'] },
  { title: 'DuckTales 2', region: ['NTSC', 'PAL'] },
  { title: 'Dungeon Magic: Sword of the Elements', region: ['NTSC'] },
  { title: "Dusty Diamond's All-Star Softball", region: ['NTSC'] },
  { title: 'Dynowarz: Destruction of Spondylus', region: ['NTSC'] },
  { title: 'Eggsplode! (part of Short Order / Eggsplode!)', region: ['NTSC'] },
  { title: 'Elevator Action', region: ['NTSC'] },
  { title: 'Eliminator Boat Duel', region: ['NTSC', 'PAL'] },
  { title: 'Elite', region: ['PAL'] },
  { title: 'Excitebike', region: ['NTSC', 'PAL'] },
  { title: 'F-15 Strike Eagle', region: ['NTSC', 'PAL'] },
  { title: 'F-117A Stealth Fighter', region: ['NTSC'] },
  { title: 'Family Feud', region: ['NTSC'] },
  { title: 'Faria: A World of Mystery and Danger', region: ['NTSC'] },
  { title: 'Faxanadu', region: ['NTSC', 'PAL'] },
  { title: 'Felix the Cat', region: ['NTSC', 'PAL'] },
  { title: 'Ferrari Grand Prix Challenge', region: ['NTSC', 'PAL'] },
  { title: "Fester's Quest", region: ['NTSC', 'PAL'] },
  { title: 'Final Fantasy', region: ['NTSC'] },
  { title: "Fire 'n Ice", region: ['NTSC'] },
  { title: "Solomon's Key 2", region: ['PAL'] },
  { title: 'Fisher-Price: Firehouse Rescue', region: ['NTSC'] },
  { title: 'Fisher-Price: I Can Remember', region: ['NTSC'] },
  { title: 'Fisher-Price: Perfect Fit', region: ['NTSC'] },
  { title: 'Fist of the North Star', region: ['NTSC'] },
  { title: 'Flight of the Intruder', region: ['NTSC'] },
  { title: 'Phantom Air Mission', region: ['PAL'] },
  { title: 'The Flintstones: The Rescue of Dino & Hoppy', region: ['NTSC', 'PAL'] },
  { title: 'The Flintstones: Surprise at Dinosaur Peak', region: ['NTSC', 'PAL'] },
  { title: 'Flying Dragon: The Secret Scroll', region: ['NTSC'] },
  { title: 'Flying Warriors', region: ['NTSC'] },
  { title: 'Formula 1 Sensation', region: ['PAL'] },
  { title: 'Formula One: Built to Win', region: ['NTSC'] },
  { title: "Fox's Peter Pan and the Pirates: The Revenge of Captain Hook", region: ['NTSC'] },
  { title: 'Frankenstein: The Monster Returns', region: ['NTSC'] },
  { title: 'Freedom Force', region: ['NTSC'] },
  { title: 'Friday the 13th', region: ['NTSC'] },
  { title: 'Fun House', region: ['NTSC'] },
  { title: 'G.I. Joe: A Real American Hero', region: ['NTSC'] },
  { title: 'G.I. Joe: The Atlantis Factor', region: ['NTSC'] },
  { title: 'Galaga: Demons of Death', region: ['NTSC'] },
  { title: 'Galaga', region: ['PAL'] },
  { title: 'Galaxy 5000', region: ['NTSC', 'PAL'] },
  { title: "Gargoyle's Quest II: The Demon Darkness", region: ['NTSC', 'PAL'] },
  { title: 'Gauntlet', region: ['NTSC'] },
  { title: 'Gauntlet II', region: ['NTSC', 'PAL'] },
  { title: 'Gemfire', region: ['NTSC'] },
  { title: 'Genghis Khan', region: ['NTSC'] },
  { title: "George Foreman's KO Boxing", region: ['NTSC', 'PAL'] },
  { title: 'Ghostbusters', region: ['NTSC'] },
  { title: 'Ghostbusters II', region: ['NTSC', 'PAL'] },
  { title: "Ghosts 'n Goblins", region: ['NTSC'] },
  { title: "Ghost 'n Goblins", region: ['PAL'] },
  { title: 'Ghoul School', region: ['NTSC'] },
  { title: 'Goal!', region: ['NTSC', 'PAL'] },
  { title: 'Goal! Two (NA/ES)', region: ['NTSC', 'PAL'] },
  { title: 'Eric Cantona Football Challenge Goal! 2 (FR)', region: ['NTSC', 'PAL'] },
  { title: 'Godzilla: Monster of Monsters', region: ['NTSC', 'PAL'] },
  { title: 'Godzilla 2: War of the Monsters', region: ['NTSC'] },
  { title: 'Golf', region: ['NTSC', 'PAL'] },
  { title: 'Golf Grand Slam', region: ['NTSC'] },
  { title: 'Golgo 13: Top Secret Episode', region: ['NTSC'] },
  { title: 'The Goonies II', region: ['NTSC', 'PAL'] },
  { title: 'Gotcha! The Sport!', region: ['NTSC'] },
  { title: 'Gradius', region: ['NTSC', 'PAL'] },
  { title: 'The Great Waldo Search', region: ['NTSC'] },
  { title: "Greg Norman's Golf Power", region: ['NTSC'] },
  { title: 'Gremlins 2: The New Batch', region: ['NTSC', 'PAL'] },
  { title: 'The Guardian Legend', region: ['NTSC', 'PAL'] },
  { title: 'Guerrilla War', region: ['NTSC', 'PAL'] },
  { title: 'Gumshoe', region: ['NTSC', 'PAL'] },
  { title: 'Gun-Nac', region: ['NTSC'] },
  { title: 'Gun.Smoke', region: ['NTSC', 'PAL'] },
  { title: 'Gyromite', region: ['NTSC', 'PAL'] },
  { title: 'Gyruss', region: ['NTSC'] },
  { title: "Hammerin' Harry", region: ['PAL'] },
  { title: 'Harlem Globetrotters', region: ['NTSC'] },
  { title: 'Hatris', region: ['NTSC'] },
  { title: 'Heavy Barrel', region: ['NTSC'] },
  { title: "Heavy Shreddin'", region: ['NTSC'] },
  { title: 'Snowboard Challenge', region: ['PAL'] },
  { title: 'High Speed', region: ['NTSC', 'PAL'] },
  { title: "Hogan's Alley", region: ['NTSC', 'PAL'] },
  { title: 'Hollywood Squares', region: ['NTSC'] },
  { title: 'Home Alone', region: ['NTSC'] },
  { title: 'Home Alone 2: Lost in New York', region: ['NTSC', 'PAL'] },
  { title: 'Hook', region: ['NTSC', 'PAL'] },
  { title: 'Hoops', region: ['NTSC', 'PAL'] },
  { title: 'Hudson Hawk', region: ['NTSC', 'PAL'] },
  { title: 'The Hunt for Red October', region: ['NTSC', 'PAL'] },
  { title: 'Hydlide', region: ['NTSC'] },
  { title: 'Ice Climber', region: ['NTSC', 'PAL'] },
  { title: 'Ice Hockey', region: ['NTSC', 'PAL'] },
  { title: 'Ikari Warriors', region: ['NTSC', 'PAL'] },
  { title: 'Ikari Warriors II: Victory Road', region: ['NTSC'] },
  { title: 'Ikari III: The Rescue', region: ['NTSC'] },
  { title: 'Image Fight', region: ['NTSC'] },
  { title: 'The Immortal', region: ['NTSC'] },
  { title: 'The Incredible Crash Dummies', region: ['NTSC', 'PAL'] },
  { title: 'Indiana Jones and the Last Crusade', region: ['NTSC'] },
  { title: 'Indiana Jones and the Last Crusade', region: ['NTSC'] },
  { title: 'Indy: Indiana Jones and the Last Crusade', region: ['PAL'] },
  { title: 'Indiana Jones and the Temple of Doom', region: ['NTSC'] },
  { title: 'Infiltrator', region: ['NTSC'] },
  { title: 'International Cricket', region: ['PAL'] },
  { title: 'Iron Tank: The Invasion of Normandy', region: ['NTSC', 'PAL'] },
  { title: 'Ironsword: Wizards & Warriors II', region: ['NTSC', 'PAL'] },
  { title: 'Isolated Warrior', region: ['NTSC', 'PAL'] },
  { title: "Ivan 'Ironman' Stewart's Super Off Road", region: ['NTSC', 'PAL'] },
  { title: "Jack Nicklaus' Greatest 18 Holes of Major Championship Golf", region: ['NTSC', 'PAL'] },
  { title: 'Jackal', region: ['NTSC'] },
  { title: "Jackie Chan's Action Kung Fu", region: ['NTSC', 'PAL'] },
  { title: 'James Bond Jr.', region: ['NTSC', 'PAL'] },
  { title: 'Jaws', region: ['NTSC'] },
  { title: 'Jeopardy!', region: ['NTSC'] },
  { title: 'Jeopardy! 25th Anniversary Edition', region: ['NTSC'] },
  { title: 'Jeopardy! Junior Edition', region: ['NTSC'] },
  { title: "The Jetsons: Cogswell's Caper!", region: ['NTSC', 'PAL'] },
  { title: 'Jimmy Connors Tennis', region: ['NTSC', 'PAL'] },
  { title: 'Joe & Mac', region: ['NTSC'] },
  { title: 'Joe & Mac: Caveman Ninja', region: ['PAL'] },
  { title: "John Elway's Quarterback", region: ['NTSC'] },
  { title: 'Jordan vs. Bird: One on One', region: ['NTSC'] },
  { title: 'Journey to Silius', region: ['NTSC', 'PAL'] },
  { title: 'Joust', region: ['NTSC'] },
  { title: 'Jurassic Park', region: ['NTSC', 'PAL'] },
  { title: 'Kabuki: Quantum Fighter', region: ['NTSC', 'PAL'] },
  { title: 'Karate Champ', region: ['NTSC'] },
  { title: 'The Karate Kid', region: ['NTSC'] },
  { title: 'Karnov', region: ['NTSC'] },
  { title: 'Kick Master', region: ['NTSC'] },
  { title: 'Kick Off', region: ['PAL'] },
  { title: 'Kickle Cubicle', region: ['NTSC', 'PAL'] },
  { title: 'Kid Icarus', region: ['NTSC', 'PAL'] },
  { title: 'Kid Klown in Night Mayor World', region: ['NTSC'] },
  { title: 'Kid Kool', region: ['NTSC'] },
  { title: 'Kid Niki: Radical Ninja', region: ['NTSC'] },
  { title: "King's Knight", region: ['NTSC'] },
  { title: "King's Quest V: Absence Makes the Heart Go Yonder!", region: ['NTSC'] },
  { title: 'Kings of the Beach', region: ['NTSC'] },
  { title: "Kirby's Adventure", region: ['NTSC', 'PAL'] },
  { title: 'Kiwi Kraze', region: ['NTSC'] },
  { title: 'The NewZealand Story', region: ['PAL'] },
  { title: 'KlashBall', region: ['NTSC'] },
  { title: 'Knight Rider', region: ['NTSC', 'PAL'] },
  { title: 'Konami Hyper Soccer', region: ['PAL'] },
  { title: 'The Krion Conquest', region: ['NTSC'] },
  { title: "Krusty's Fun House", region: ['NTSC', 'PAL'] },
  { title: 'Kung Fu', region: ['NTSC', 'PAL'] },
  { title: 'Kung-Fu Heroes', region: ['NTSC'] },
  { title: 'Laser Invasion', region: ['NTSC'] },
  { title: 'Last Action Hero', region: ['NTSC'] },
  { title: 'The Last Ninja', region: ['NTSC'] },
  { title: 'The Last Starfighter', region: ['NTSC'] },
  { title: "Lee Trevino's Fighting Golf", region: ['NTSC', 'PAL'] },
  { title: 'Legacy of the Wizard', region: ['NTSC'] },
  { title: 'The Legend of Kage', region: ['NTSC'] },
  { title: 'The Legend of Prince Valiant', region: ['PAL'] },
  { title: 'Legend of the Ghost Lion', region: ['NTSC'] },
  { title: 'The Legend of Zelda', region: ['NTSC', 'PAL'] },
  { title: 'Legendary Wings', region: ['NTSC'] },
  { title: 'Legends of the Diamond', region: ['NTSC'] },
  { title: 'Lemmings', region: ['NTSC', 'PAL'] },
  { title: "L'Empereur", region: ['NTSC'] },
  { title: "Les Chevaliers du Zodiaque: La Légende d'or", region: ['PAL'] },
  { title: 'Lethal Weapon', region: ['NTSC', 'PAL'] },
  { title: 'Life Force', region: ['NTSC'] },
  { title: 'Life Force Salamander', region: ['PAL'] },
  { title: 'Little League Baseball: Championship Series', region: ['NTSC'] },
  { title: 'Little Nemo: The Dream Master', region: ['NTSC', 'PAL'] },
  { title: 'Little Ninja Brothers', region: ['NTSC', 'PAL'] },
  { title: 'Little Samson', region: ['NTSC', 'PAL'] },
  { title: 'Lode Runner', region: ['NTSC'] },
  { title: 'The Lone Ranger', region: ['NTSC'] },
  { title: 'Loopz', region: ['NTSC'] },
  { title: 'Low G Man: The Low Gravity Man', region: ['NTSC', 'PAL'] },
  { title: 'Lunar Pool', region: ['NTSC', 'PAL'] },
  { title: 'M.C. Kids', region: ['NTSC'] },
  { title: 'McDonaldland', region: ['PAL'] },
  { title: 'M.U.L.E.', region: ['NTSC'] },
  { title: 'M.U.S.C.L.E.', region: ['NTSC'] },
  { title: 'Mach Rider', region: ['NTSC', 'PAL'] },
  { title: 'Mad Max', region: ['NTSC'] },
  { title: 'The Mafat Conspiracy: Golgo 13', region: ['NTSC'] },
  { title: 'Magic Darts', region: ['NTSC'] },
  { title: "Magic Johnson's Fast Break", region: ['NTSC'] },
  { title: 'The Magic of Scheherazade', region: ['NTSC'] },
  { title: 'Magician', region: ['NTSC'] },
  { title: 'MagMax', region: ['NTSC'] },
  { title: 'Mah Jong', region: [] },
  { title: 'Major League Baseball', region: ['NTSC'] },
  { title: 'Maniac Mansion', region: ['NTSC', 'PAL'] },
  { title: 'Mappy-Land', region: ['NTSC'] },
  { title: 'Marble Madness', region: ['NTSC', 'PAL'] },
  { title: 'Mario Bros.', region: ['NTSC', 'PAL'] },
  { title: 'Mario Bros. (Classic Series)', region: ['PAL'] },
  { title: 'Mario Is Missing!', region: ['NTSC', 'PAL'] },
  { title: "Mario's Time Machine", region: ['NTSC'] },
  { title: 'Mechanized Attack', region: ['NTSC'] },
  { title: 'Mega Man', region: ['NTSC', 'PAL'] },
  { title: 'Mega Man 2', region: ['NTSC', 'PAL'] },
  { title: 'Mega Man 3', region: ['NTSC', 'PAL'] },
  { title: 'Mega Man 4', region: ['NTSC', 'PAL'] },
  { title: 'Mega Man 5', region: ['NTSC', 'PAL'] },
  { title: 'Mega Man 6', region: ['NTSC'] },
  { title: 'Mendel Palace', region: ['NTSC'] },
  { title: 'Metal Gear', region: ['NTSC', 'PAL'] },
  { title: 'Metal Mech: Man & Machine', region: ['NTSC'] },
  { title: 'Metal Storm', region: ['NTSC'] },
  { title: 'Metroid', region: ['NTSC', 'PAL'] },
  { title: "Michael Andretti's World GP", region: ['NTSC'] },
  { title: 'Mickey Mousecapade', region: ['NTSC'] },
  { title: "Mickey's Adventures in Numberland", region: ['NTSC'] },
  { title: "Mickey's Safari in Letterland", region: ['NTSC'] },
  { title: 'Might and Magic Book One: The Secret of the Inner Sanctum', region: ['NTSC'] },
  { title: 'Mighty Bomb Jack', region: ['NTSC', 'PAL'] },
  { title: 'Mighty Final Fight', region: ['NTSC', 'PAL'] },
  { title: "Mike Tyson's Punch-Out!!", region: ['NTSC', 'PAL'] },
  { title: 'Millipede', region: ['NTSC'] },
  { title: "Milon's Secret Castle", region: ['NTSC'] },
  { title: 'The Miracle Piano Teaching System', region: ['NTSC', 'PAL'] },
  { title: 'Mission: Impossible', region: ['NTSC', 'PAL'] },
  { title: 'Monopoly', region: ['NTSC', 'PAL'] },
  { title: 'Monster in My Pocket', region: ['NTSC', 'PAL'] },
  { title: 'Monster Party', region: ['NTSC'] },
  { title: 'Monster Truck Rally', region: ['NTSC'] },
  { title: 'Motor City Patrol', region: ['NTSC'] },
  { title: 'Mr. Gimmick', region: ['PAL'] },
  { title: 'Ms. Pac-Man', region: ['NTSC'] },
  { title: 'Muppet Adventure: Chaos at the Carnival', region: ['NTSC'] },
  { title: 'The Mutant Virus: Crisis in a Computer World', region: ['NTSC'] },
  { title: 'Mystery Quest', region: ['NTSC'] },
  { title: 'NARC', region: ['NTSC'] },
  { title: 'NES Open Tournament Golf', region: ['NTSC', 'PAL'] },
  { title: 'NES Play Action Football', region: ['NTSC'] },
  { title: 'New Ghostbusters II', region: ['PAL'] },
  { title: 'NFL Football', region: ['NTSC'] },
  { title: "Nigel Mansell's World Championship Racing", region: ['NTSC', 'PAL'] },
  { title: 'A Nightmare on Elm Street', region: ['NTSC'] },
  { title: 'Nightshade', region: ['NTSC'] },
  { title: 'Ninja Crusaders', region: ['NTSC'] },
  { title: 'Ninja Gaiden', region: ['NTSC'] },
  { title: 'Shadow Warriors', region: ['PAL'] },
  { title: 'Ninja Gaiden II: The Dark Sword of Chaos', region: ['NTSC'] },
  { title: 'Shadow Warriors II', region: ['PAL'] },
  { title: 'Ninja Gaiden III: The Ancient Ship of Doom', region: ['NTSC'] },
  { title: 'Ninja Kid', region: ['NTSC'] },
  { title: 'Nintendo World Cup', region: ['NTSC', 'PAL'] },
  { title: "Noah's Ark", region: ['PAL'] },
  { title: "Nobunaga's Ambition", region: ['NTSC'] },
  { title: "Nobunaga's Ambition II", region: ['NTSC'] },
  { title: 'North & South', region: ['NTSC', 'PAL'] },
  { title: 'Operation Wolf', region: ['NTSC', 'PAL'] },
  { title: 'Orb-3D', region: ['NTSC'] },
  { title: 'Othello', region: ['NTSC'] },
  { title: 'Over Horizon', region: ['PAL'] },
  { title: 'Overlord', region: ['NTSC'] },
  { title: 'P.O.W.: Prisoners of War', region: ['NTSC', 'PAL'] },
  { title: 'Pac-Man', region: ['NTSC'] },
  { title: 'Pac-Man', region: ['NTSC', 'PAL'] },
  { title: 'Palamedes', region: ['NTSC'] },
  { title: 'Panic Restaurant', region: ['NTSC', 'PAL'] },
  { title: 'Paperboy', region: ['NTSC', 'PAL'] },
  { title: 'Paperboy 2', region: ['NTSC', 'PAL'] },
  { title: 'Parasol Stars: Rainbow Island II', region: ['PAL'] },
  { title: 'Parodius', region: ['PAL'] },
  { title: 'Phantom Fighter', region: ['NTSC'] },
  { title: 'Pictionary', region: ['NTSC'] },
  { title: 'Pinball', region: ['NTSC', 'PAL'] },
  { title: 'Pinball Quest', region: ['NTSC', 'PAL'] },
  { title: 'Pin*Bot', region: ['NTSC', 'PAL'] },
  { title: 'Pipe Dream', region: ['NTSC'] },
  { title: 'Pirates!', region: ['NTSC'] },
  { title: 'Platoon', region: ['NTSC'] },
  { title: 'Popeye', region: ['NTSC', 'PAL'] },
  { title: 'Power Blade', region: ['NTSC', 'PAL'] },
  { title: 'Power Blade 2', region: ['NTSC'] },
  { title: 'Power Punch II', region: ['NTSC'] },
  { title: 'Predator', region: ['NTSC', 'PAL'] },
  { title: 'Prince of Persia', region: ['NTSC', 'PAL'] },
  { title: 'Princess Tomato in the Salad Kingdom', region: ['NTSC'] },
  { title: 'Pro Sport Hockey', region: ['NTSC'] },
  { title: 'Pro Wrestling', region: ['NTSC', 'PAL'] },
  { title: 'Punch-Out!! Featuring Mr. Dream', region: ['NTSC', 'PAL'] },
  { title: 'The Punisher', region: ['NTSC'] },
  { title: "Puss 'n Boots: Pero's Great Adventure", region: ['NTSC'] },
  { title: 'Puzznic', region: ['NTSC', 'PAL'] },
  { title: 'Q*bert', region: ['NTSC'] },
  { title: 'Qix', region: ['NTSC'] },
  { title: 'R.B.I. Baseball', region: ['NTSC'] },
  { title: 'R.C. Pro-Am', region: ['NTSC', 'PAL'] },
  { title: 'R.C. Pro-Am II', region: ['NTSC', 'PAL'] },
  { title: 'Racket Attack', region: ['NTSC', 'PAL'] },
  { title: 'Rackets & Rivals', region: ['PAL'] },
  { title: 'Rad Racer', region: ['NTSC', 'PAL'] },
  { title: 'Rad Racer II', region: ['NTSC'] },
  { title: 'Raid on Bungeling Bay', region: ['NTSC'] },
  { title: 'Rainbow Islands', region: ['NTSC'] },
  { title: 'Rainbow Islands: Bubble Bobble 2', region: ['PAL'] },
  { title: 'Rally Bike', region: ['NTSC'] },
  { title: 'Rambo', region: ['NTSC'] },
  { title: 'Rampage', region: ['NTSC'] },
  { title: 'Rampart', region: ['NTSC', 'PAL'] },
  { title: 'Remote Control', region: ['NTSC'] },
  { title: 'The Ren & Stimpy Show: Buckeroo$!', region: ['NTSC'] },
  { title: 'Renegade', region: ['NTSC'] },
  { title: 'Rescue: The Embassy Mission', region: ['NTSC', 'PAL'] },
  { title: 'Ring King', region: ['NTSC'] },
  { title: 'River City Ransom', region: ['NTSC'] },
  { title: 'Street Gangs', region: ['PAL'] },
  { title: 'Road Fighter', region: ['PAL'] },
  { title: 'RoadBlasters', region: ['NTSC', 'PAL'] },
  { title: 'Robin Hood: Prince of Thieves', region: ['NTSC', 'PAL'] },
  { title: 'RoboCop', region: ['NTSC', 'PAL'] },
  { title: 'RoboCop 2', region: ['NTSC', 'PAL'] },
  { title: 'RoboCop 3', region: ['NTSC', 'PAL'] },
  { title: 'Robowarrior', region: ['NTSC', 'PAL'] },
  { title: "Rock 'n' Ball", region: ['NTSC'] },
  { title: 'Rocket Ranger', region: ['NTSC'] },
  { title: 'The Rocketeer', region: ['NTSC'] },
  { title: "Rockin' Kats", region: ['NTSC', 'PAL'] },
  { title: 'Rod Land', region: ['PAL'] },
  { title: "Roger Clemens' MVP Baseball", region: ['NTSC'] },
  { title: 'Rollerball', region: ['NTSC', 'PAL'] },
  { title: 'Rollerblade Racer', region: ['NTSC'] },
  { title: 'RollerGames', region: ['NTSC', 'PAL'] },
  { title: 'Romance of the Three Kingdoms', region: ['NTSC'] },
  { title: 'Romance of the Three Kingdoms II', region: ['NTSC'] },
  { title: 'Roundball: 2 on 2 Challenge', region: ['NTSC', 'PAL'] },
  { title: "Rush'n Attack", region: ['NTSC', 'PAL'] },
  { title: 'Rygar', region: ['NTSC', 'PAL'] },
  { title: 'S.C.A.T.: Special Cybernetic Attack Team', region: ['NTSC'] },
  { title: 'Action in New York', region: ['PAL'] },
  { title: 'Section Z', region: ['NTSC', 'PAL'] },
  { title: 'Seicross', region: ['NTSC'] },
  { title: 'Sesame Street: 1-2-3', region: ['NTSC'] },
  { title: 'Sesame Street: A-B-C', region: ['NTSC'] },
  { title: 'Sesame Street: A-B-C/1-2-3', region: ['NTSC'] },
  { title: "Sesame Street: Big Bird's Hide & Speak", region: ['NTSC'] },
  { title: 'Sesame Street: Countdown', region: ['NTSC'] },
  { title: 'Shadow of the Ninja', region: ['NTSC'] },
  { title: 'Blue Shadow', region: ['PAL'] },
  { title: 'Shadowgate', region: ['NTSC', 'PAL'] },
  { title: 'Shatterhand', region: ['NTSC', 'PAL'] },
  { title: 'Shingen the Ruler', region: ['NTSC'] },
  { title: 'Shooting Range', region: ['NTSC'] },
  { title: 'Short Order (part of Short Order / Eggsplode!)', region: ['NTSC'] },
  { title: 'Side Pocket', region: ['NTSC', 'PAL'] },
  { title: 'Silent Service', region: ['NTSC', 'PAL'] },
  { title: 'Silkworm', region: ['NTSC'] },
  { title: 'Silver Surfer', region: ['NTSC'] },
  { title: 'The Simpsons: Bart vs. the Space Mutants', region: ['NTSC', 'PAL'] },
  { title: 'The Simpsons: Bart vs. the World', region: ['NTSC', 'PAL'] },
  { title: 'The Simpsons: Bartman Meets Radioactive Man', region: ['NTSC', 'PAL'] },
  { title: 'Skate or Die!', region: ['NTSC', 'PAL'] },
  { title: 'Skate or Die 2: The Search for Double Trouble', region: ['NTSC'] },
  { title: 'Ski or Die', region: ['NTSC', 'PAL'] },
  { title: 'Sky Kid', region: ['NTSC'] },
  { title: 'Sky Shark', region: ['NTSC'] },
  { title: 'Slalom', region: ['NTSC', 'PAL'] },
  { title: 'Smash TV', region: ['NTSC', 'PAL'] },
  { title: 'The Smurfs', region: ['PAL'] },
  { title: "Snake Rattle 'n' Roll", region: ['NTSC', 'PAL'] },
  { title: "Snake's Revenge", region: ['NTSC', 'PAL'] },
  { title: "Snoopy's Silly Sports Spectacular", region: ['NTSC'] },
  { title: 'Snow Brothers', region: ['NTSC', 'PAL'] },
  { title: 'Soccer', region: ['NTSC', 'PAL'] },
  { title: 'Solar Jetman: Hunt for the Golden Warpship', region: ['NTSC', 'PAL'] },
  { title: "Solomon's Key", region: ['NTSC', 'PAL'] },
  { title: 'Solstice: The Quest for the Staff of Demnos', region: ['NTSC', 'PAL'] },
  { title: 'Space Shuttle Project', region: ['NTSC'] },
  { title: 'Spelunker', region: ['NTSC'] },
  { title: 'Spider-Man: Return of the Sinister Six', region: ['NTSC', 'PAL'] },
  { title: 'Spot: The Video Game', region: ['NTSC'] },
  { title: 'Spy Hunter', region: ['NTSC'] },
  { title: 'Spy vs. Spy', region: ['NTSC', 'PAL'] },
  { title: 'Sqoon', region: ['NTSC'] },
  { title: 'Stack-Up', region: ['NTSC', 'PAL'] },
  { title: 'Stadium Events', region: ['NTSC', 'PAL'] },
  { title: 'Stanley: The Search for Dr. Livingston', region: ['NTSC'] },
  { title: 'Star Force', region: ['NTSC', 'PAL'] },
  { title: 'Star Soldier', region: ['NTSC'] },
  { title: 'Star Trek: 25th Anniversary', region: ['NTSC', 'PAL'] },
  { title: 'Star Trek: The Next Generation', region: ['NTSC'] },
  { title: 'Star Voyager', region: ['NTSC'] },
  { title: 'Star Wars', region: ['NTSC', 'PAL'] },
  { title: 'Star Wars: The Empire Strikes Back', region: ['NTSC', 'PAL'] },
  { title: 'Starship Hector', region: ['NTSC'] },
  { title: 'StarTropics', region: ['NTSC', 'PAL'] },
  { title: 'Stealth ATF', region: ['NTSC', 'PAL'] },
  { title: 'Stinger', region: ['NTSC'] },
  { title: 'Street Cop', region: ['NTSC'] },
  { title: 'Street Fighter 2010: The Final Fight', region: ['NTSC'] },
  { title: 'Strider', region: ['NTSC'] },
  { title: 'Super C', region: ['NTSC'] },
  { title: 'Probotector II: Return of The Evil Forces', region: ['PAL'] },
  { title: 'Super Cars', region: ['NTSC'] },
  { title: 'Super Dodge Ball', region: ['NTSC'] },
  { title: 'Super Glove Ball', region: ['NTSC'] },
  { title: 'Super Jeopardy!', region: ['NTSC'] },
  { title: 'Super Mario Bros.', region: ['NTSC', 'PAL'] },
  { title: 'Super Mario Bros./Duck Hunt', region: ['NTSC', 'PAL'] },
  { title: 'Super Mario Bros./Duck Hunt/World Class Track Meet', region: ['NTSC'] },
  { title: 'Super Mario Bros./Tetris/Nintendo World Cup', region: ['PAL'] },
  { title: 'Super Mario Bros. 2', region: ['NTSC', 'PAL'] },
  { title: 'Super Mario Bros. 3', region: ['NTSC', 'PAL'] },
  { title: 'Super Pitfall', region: ['NTSC'] },
  { title: "Super Spike V'Ball", region: ['NTSC', 'PAL'] },
  { title: "Super Spike V'Ball/Nintendo World Cup", region: ['NTSC'] },
  { title: 'Super Spy Hunter', region: ['NTSC', 'PAL'] },
  { title: 'Super Team Games', region: ['NTSC'] },
  { title: 'Super Turrican', region: ['PAL'] },
  { title: 'Superman', region: ['NTSC'] },
  { title: 'Swamp Thing', region: ['NTSC', 'PAL'] },
  { title: 'Sword Master', region: ['NTSC', 'PAL'] },
  { title: 'Swords and Serpents', region: ['NTSC', 'PAL'] },
  { title: 'Taboo: The Sixth Sense', region: ['NTSC'] },
  { title: 'Tag Team Wrestling', region: ['NTSC'] },
  { title: 'TaleSpin', region: ['NTSC', 'PAL'] },
  { title: 'Target: Renegade', region: ['NTSC'] },
  { title: 'Tecmo Baseball', region: ['NTSC'] },
  { title: 'Tecmo Bowl', region: ['NTSC'] },
  { title: 'Tecmo Cup Soccer Game', region: ['NTSC'] },
  { title: 'Tecmo Cup: Football Game', region: ['PAL'] },
  { title: 'Tecmo NBA Basketball', region: ['NTSC'] },
  { title: 'Tecmo Super Bowl', region: ['NTSC'] },
  { title: 'Tecmo World Cup Soccer', region: ['PAL'] },
  { title: 'Tecmo World Wrestling', region: ['NTSC', 'PAL'] },
  { title: 'Teenage Mutant Ninja Turtles (NA/AU)', region: ['NTSC', 'PAL'] },
  { title: 'Teenage Mutant Hero Turtles', region: ['PAL'] },
  { title: 'Teenage Mutant Ninja Turtles II: The Arcade Game (NA/AU)', region: ['NTSC', 'PAL'] },
  { title: 'Teenage Mutant Hero Turtles II: The Arcade Game', region: ['PAL'] },
  { title: 'Teenage Mutant Ninja Turtles III: The Manhattan Project', region: ['NTSC'] },
  { title: 'Teenage Mutant Ninja Turtles: Tournament Fighters', region: ['NTSC'] },
  { title: 'Teenage Mutant Hero Turtles: Tournament Fighters', region: ['PAL'] },
  { title: 'Tennis', region: ['NTSC', 'PAL'] },
  { title: 'The Terminator', region: ['NTSC', 'PAL'] },
  { title: 'Terminator 2: Judgment Day', region: ['NTSC', 'PAL'] },
  { title: 'Terra Cresta', region: ['NTSC'] },
  { title: 'Tetris', region: ['NTSC', 'PAL'] },
  { title: 'Tetris 2', region: ['NTSC', 'PAL'] },
  { title: 'The Three Stooges', region: ['NTSC'] },
  { title: 'Thunder & Lightning', region: ['NTSC'] },
  { title: 'Thunderbirds', region: ['NTSC'] },
  { title: 'Thundercade', region: ['NTSC'] },
  { title: 'Tiger-Heli', region: ['NTSC', 'PAL'] },
  { title: 'Time Lord', region: ['NTSC', 'PAL'] },
  { title: 'Times of Lore', region: ['NTSC'] },
  { title: 'Tiny Toon Adventures', region: ['NTSC', 'PAL'] },
  { title: 'Tiny Toon Adventures 2: Trouble in Wackyland', region: ['NTSC', 'PAL'] },
  { title: 'Tiny Toon Adventures Cartoon Workshop', region: ['NTSC', 'PAL'] },
  { title: 'To the Earth', region: ['NTSC', 'PAL'] },
  { title: 'Toki', region: ['NTSC'] },
  { title: 'Tom and Jerry', region: ['NTSC', 'PAL'] },
  { title: 'Tombs & Treasure', region: ['NTSC'] },
  { title: 'Top Gun', region: ['NTSC', 'PAL'] },
  { title: 'Top Gun: The Second Mission', region: ['NTSC', 'PAL'] },
  { title: "Top Players' Tennis", region: ['NTSC'] },
  { title: "Four Players' Tennis", region: ['PAL'] },
  { title: 'Total Recall', region: ['NTSC', 'PAL'] },
  { title: 'Totally Rad', region: ['NTSC', 'PAL'] },
  { title: 'Touch Down Fever', region: ['NTSC'] },
  { title: 'Town & Country Surf Designs: Wood & Water Rage', region: ['NTSC'] },
  { title: "Town & Country II: Thrilla's Surfari", region: ['NTSC'] },
  { title: 'Toxic Crusaders', region: ['NTSC'] },
  { title: 'Track & Field', region: ['NTSC'] },
  { title: 'Track & Field in Barcelona', region: ['PAL'] },
  { title: 'Track & Field II', region: ['NTSC', 'PAL'] },
  { title: 'Treasure Master', region: ['NTSC'] },
  { title: 'Trog!', region: ['NTSC', 'PAL'] },
  { title: 'Trojan', region: ['NTSC', 'PAL'] },
  { title: 'The Trolls in Crazyland', region: ['PAL'] },
  { title: 'Twin Cobra', region: ['NTSC'] },
  { title: 'Twin Eagle', region: ['NTSC'] },
  { title: 'Ufouria: The Saga', region: ['PAL'] },
  { title: 'Ultima III: Exodus', region: ['NTSC'] },
  { title: 'Ultima IV: Quest of the Avatar', region: ['NTSC'] },
  { title: 'Ultima V: Warriors of Destiny', region: ['NTSC'] },
  { title: 'Ultimate Air Combat', region: ['NTSC', 'PAL'] },
  { title: 'Ultimate Basketball', region: ['NTSC'] },
  { title: 'The Uncanny X-Men', region: ['NTSC'] },
  { title: 'Uncharted Waters', region: ['NTSC'] },
  { title: 'Uninvited', region: ['NTSC'] },
  { title: 'The Untouchables', region: ['NTSC'] },
  { title: 'Urban Champion', region: ['NTSC', 'PAL'] },
  { title: 'Vegas Dream', region: ['NTSC'] },
  { title: 'Vice: Project Doom', region: ['NTSC'] },
  { title: 'Videomation', region: ['NTSC'] },
  { title: 'Volleyball', region: ['NTSC', 'PAL'] },
  { title: 'Wacky Races', region: ['NTSC'] },
  { title: 'Wall Street Kid', region: ['NTSC'] },
  { title: "Wario's Woods", region: ['NTSC', 'PAL'] },
  { title: 'Wayne Gretzky Hockey', region: ['NTSC'] },
  { title: "Wayne's World", region: ['NTSC'] },
  { title: 'WCW Wrestling', region: ['NTSC'] },
  { title: 'Werewolf: The Last Warrior', region: ['NTSC', 'PAL'] },
  { title: 'Wheel of Fortune', region: ['NTSC'] },
  { title: 'Wheel of Fortune Family Edition', region: ['NTSC'] },
  { title: 'Wheel of Fortune: Featuring Vanna White', region: ['NTSC'] },
  { title: 'Wheel of Fortune Junior Edition', region: ['NTSC'] },
  { title: 'Where in Time Is Carmen Sandiego?', region: ['NTSC'] },
  { title: "Where's Waldo?", region: ['NTSC'] },
  { title: 'Who Framed Roger Rabbit', region: ['NTSC'] },
  { title: "Whomp 'Em", region: ['NTSC'] },
  { title: 'Widget', region: ['NTSC'] },
  { title: 'Wild Gunman', region: ['NTSC', 'PAL'] },
  { title: 'Willow', region: ['NTSC', 'PAL'] },
  { title: 'Win, Lose, or Draw', region: ['NTSC'] },
  { title: 'Winter Games', region: ['NTSC'] },
  { title: 'Wizardry: Proving Grounds of the Mad Overlord', region: ['NTSC'] },
  { title: 'Wizardry II: The Knight of Diamonds', region: ['NTSC'] },
  { title: 'Wizards & Warriors', region: ['NTSC', 'PAL'] },
  { title: 'Wizards & Warriors III: Kuros: Visions of Power', region: ['NTSC'] },
  { title: 'Wizards & Warriors III', region: ['PAL'] },
  { title: 'Wolverine', region: ['NTSC'] },
  { title: 'World Champ', region: ['NTSC', 'PAL'] },
  { title: 'World Class Track Meet', region: ['NTSC'] },
  { title: 'World Games', region: ['NTSC'] },
  { title: 'Wrath of the Black Manta', region: ['NTSC', 'PAL'] },
  { title: 'Wrecking Crew', region: ['NTSC', 'PAL'] },
  { title: 'Wurm: Journey to the Center of the Earth', region: ['NTSC'] },
  { title: 'WWF King of the Ring', region: ['NTSC', 'PAL'] },
  { title: 'WWF WrestleMania', region: ['NTSC', 'PAL'] },
  { title: 'WWF WrestleMania Challenge', region: ['NTSC', 'PAL'] },
  { title: 'WWF WrestleMania: Steel Cage Challenge', region: ['NTSC', 'PAL'] },
  { title: 'Xenophobe', region: ['NTSC'] },
  { title: 'Xevious', region: ['NTSC', 'PAL'] },
  { title: 'Xexyz', region: ['NTSC'] },
  { title: 'Yo! Noid', region: ['NTSC'] },
  { title: 'Yoshi', region: ['NTSC'] },
  { title: 'Mario & Yoshi', region: ['PAL'] },
  { title: "Yoshi's Cookie", region: ['NTSC', 'PAL'] },
  { title: 'The Young Indiana Jones Chronicles', region: ['NTSC'] },
  { title: 'Zanac', region: ['NTSC'] },
  { title: 'Zelda II: The Adventure of Link', region: ['NTSC', 'PAL'] },
  { title: 'Zen the Intergalactic Ninja', region: ['NTSC', 'PAL'] },
  { title: "Zoda's Revenge: StarTropics II", region: ['NTSC'] },
  { title: 'Zombie Nation', region: ['NTSC'] },
]
